# Generated by Django 5.0.3 on 2024-04-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent',
            name='total_sent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
